### ISSUE TITLE
Create a MVP for testing SOS rules with STS

### ISSUE THREAD

**Issue by dnadales** [input-output-hk/decentralized-software-updates#98]
It might be possible to test our SOS rules with state machines (also called data automata). This will allow us to:

- Define properties in a simpler way
- Have a more understandable specification since SM's are more amenable to a wider range of people (it's a visual formalism which is easier to grasp).
- Have several levels of assurance: e.g.: 
  - level 0: just SOS rules
  - level 1: state machine spec of the properties + conformance tests SOS <-> SM
  - level 2: properties on the SM traces 
  - level 3: model checked properties (using the SM as model and tools such as [`uppaal`](http://www.uppaal.org/) or [`mcrl2`](https://www.mcrl2.org/web/user_manual/index.html).
- Decouple generator code from SOS rules code: generators would be defined on state machines (furthermore the idea is to automate as much as possible the process of obtaining generators from SM's)
- More efficient generators, since the state machines determine quite straightforwardly the next possible events. At the moment we have to rummage the SOS states to determine this.
- Remove rules such as `CHAIN` or `TRANSACTION` that are there only for the sake of testing the SOS rules (the consensus layer won't use the ledger rules but the update rules interface).

In addition an stretched objectives are:

- be able to generate LaTeX diagrams automatically from these state machines.
- define state machines that can be stepped through to explore the design

## Tasks

- [x] Define the data automata formalism in Haskell
- [x] Define an interpreter that runs the state automata
- [x] Add a notion of input and output actions.
- [x] Define a bare bones interpreter that generates actions given a certain state
- [x] Add operator for union (needed for modelling voting)
- [x] Add operator for function application (needed for voting)
- [x] Define a parallel composition operator
- [x] Extend the `Run` interpreter to be able to run a model with the parallel composition operator.
- [x] Make a *full* model of the commit reveal state automata
- [x] Extend the `Gen` interpreter to be able to generate actions from a parallel composition of automata.
- [x] Make a *full* model of the voting state automata (if we're not able to model this, then the whole approach has no point).
  - [x] Model the vote tallying aspect.
  - [x] Model the timing aspect of the voting phase (voting period active, voting period end, tallying phase).
  - [x] Compose tallying and vote timing, check liveness properties (via QC).
  - [x] Compose commit-reveal and the voting model described above.
  - [x] Compose multiple automata corresponding to multiple SIP's.
- [ ] Prove conformance SM/SOS for commit-reveal model
  - [x] Define shrinkers for SM traces 
  - [x] Define a generator for traces with invalid signals (zero or more)
  - [x] Define a translation from SM concrete actions to SOS labels (a.k.a. signals).
  - [x] Write the SM/SOS conformance tests (this could be done using `quickcheck-state-machine` or just defining our own tests, since the former might be overkill and bring unnecessary complexity).
  - [x] Fix bug in the SOS rules, where a reveal can be immediately submitted after a commit when the commit slot is `< 2k `.
- [x] Tidy up the code to make it suitable for a presentation.
- [x] Evaluate go/nogo.

## Roadmap implications
https://github.com/input-output-hk/decentralized-software-updates/issues/37 would have to be postponed till we reach a decision on whether to discard the existing generators in favor of state machine generators

## Features that will need to be added in case of positive decision
If we decide to use this approach then we will need to:

- [ ] Define a smart constructor for runnable automata which check types. For instance, at the moment we get errors when there are undefined variables used in the automata transitions.
- [ ] Define a structure that allows to cache information such as automata actions, or reachable actions in a given state.
- [ ] Write an interpreter that elaborates TikZ diagrams.

**Comment by dnadales** [comment]
Addressed in https://github.com/input-output-hk/decentralized-software-updates/pull/90
